name: cellsegmentation
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - numpy
  - pillow
  - opencv
  - matplotlib
  - scikit-image
  - imageio
  - scipy
  - scikit-learn
  - tifffile
  - tqdm
variables:
  MPLBACKEND: Agg
