name: tracking_visualization
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - tifffile>=2022.5.4
  - pip
  - pip:
    - matplotlib
    