name: tracking_with_trackstra_minimal
channels:
  - conda-forge
  - pytorch
  - bioconda
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - scikit-image
  - tifffile
  - pip
  - pip:
    - trackastra
variables:
  MPLBACKEND: Agg
