name: instance-label-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - opencv
  - scikit-image
  - imageio
  - scipy
  - scikit-learn
  - tifffile
  - tqdm
  - matplotlib
  - pip
  - pip:
    - pyclesperanto-prototype
    - napari  # Optional, only needed for development/debugging
